title: The Orange Bird
theme: minima
author: Nicky Straub
email: nickystraub560@gmail.com
description: > # this means to ignore newlines until "baseurl:"
A blog about all things Swift, SWE, and building awesome apps!

# social links
instagram_username: nickystraub # DO NOT include the @ character, or else the build will fail!
github_username:  nickystraub # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
